- hosts: db_group:app_group
  become: true
  gather_facts: false
  tasks:
    - name: Run db role
      include_role:
        name: db
      when: inventory_hostname in groups['db_group']

    - name: Run app role
      include_role:
        name: app
      when: inventory_hostname in groups['app_group']

- hosts: web_group
  become: true
  roles:
    - web